apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
        labels:
          app: hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: jfdona23/flask-hello-world:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
---
kind: kind: Service
apiVersion: v1
metadata:
  name:  flask-hello-world
spec:
  selector:
    app:  hello-world
  type:  NodePort
  ports:
    targetPort:  8000